name: Reusable • Node CI

on:
  workflow_call:
    inputs:
      node_version:
        required: false
        type: string
        default: "20"
    secrets:
      NPM_TOKEN:
        required: false

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: "pnpm"
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - run: pnpm install --frozen-lockfile
      - run: pnpm -r lint || pnpm lint
      - run: pnpm -r test || pnpm test
      - name: Build
        run: pnpm -r build || pnpm build
